version: '3.8'

services:
  font-identifier:
    build: .
    container_name: font-identifier-app
    ports:
      - "8501:8501"
    volumes:
      - ./recordings:/app/recordings
      - ./config:/app/config
      - ./app_users.db:/app/app_users.db
      - ./model.pth:/app/model.pth
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - TERM=xterm
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_ENABLE_WEBSOCKET_COMPRESSION=false
      - TORCH_HOME=/app/torch_cache
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - OMP_NUM_THREADS=1
      - DISPLAY=:99
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: font-identifier-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - font-identifier
    restart: unless-stopped
    profiles:
      - production

volumes:
  recordings:
  config:

networks:
  default:
    name: font-identifier-network
