version: '3.8'

services:
  font-identifier:
    build: 
      context: .
      target: runtime
    container_name: font-identifier-app
    ports:
      - "8501:8501"
    volumes:
      - ./recordings:/app/recordings
      - ./config:/app/config
      - ./app_users.db:/app/app_users.db
      - ./model.pth:/app/model.pth
      - font-cache:/app/torch_cache
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - TORCH_HOME=/app/torch_cache
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - OMP_NUM_THREADS=1
      - MPLBACKEND=Agg
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501/_stcore/health || curl -f http://localhost:8501/ || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 90s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: font-identifier-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - font-identifier
    restart: unless-stopped
    profiles:
      - production

volumes:
  recordings:
  config:
  font-cache:

networks:
  default:
    name: font-identifier-network
